##
##  Makefile -- Build procedure for sample dynaconf Apache module
##  Autogenerated via ``apxs -n dynaconf -g''.
##

builddir=.
top_srcdir=/home/admin/opt/httpd-2.2.21
top_builddir=/home/admin/opt/httpd-2.2.21
include /home/admin/opt/httpd-2.2.21/build/special.mk

#   the used tools
APXS=apxs
APACHECTL=apachectl

#   additional defines, includes and libraries
#DEFS=-Dmy_define=my_value
#INCLUDES=-Imy/include/dir
#LIBS=-Lmy/lib/dir -lmylib

#   the default target
all: local-shared-build

#   install the shared object file into Apache 
install: install-modules-yes

#   cleanup
clean:
	-rm -f mod_dynaconf.o mod_dynaconf.lo mod_dynaconf.slo mod_dynaconf.la 

#   simple test
test: reload
	lynx -mime_header http://localhost/dynaconf

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

